//! Generated types from the NEAR Protocol OpenRPC schema.
//!
//! This module is auto-generated by `typify` from `openrpc.json` at build time.
//! Do not edit `generated.rs` manually — it will be overwritten.

#[allow(
    clippy::infallible_try_from,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::derivable_impls
)]
mod inner {
    include!("generated.rs");
}
pub use inner::*;
